name: 🧪 Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/checkout@v3
      - run: python3 -m pip install matplotlib flake8 pytest numpy isort mypy pydocstyle
      - run: python3 -m flake8 .
        name: Run flake8 checks
      - run: python3 -m pydocstyle .
        name: Run pydocstyle checks
      - run: python3 -m mypy .
        name: Run mypy checks
      - run: python3 -m isort --check .
        name: Run isort checks
      - run: python3 -m pytest test
        name: Run tests
      - run: |
          python3 make_pngs.py
          python3 make_readme_png.py
        name: Run scripts
